### ISSUE TITLE
Generic Patches

### ISSUE THREAD

**Issue by Pafke01** [MarisElsins/getMOSPatch#16]
Generic patches are causing a litle issue.
Example: 30170398 WEBLOGIC SAMPLES SPU 12.2.1.3.191015

config:
226P;Linux x86-64
233P;Microsoft Windows x64 (64-bit)
209P;IBM: Linux on System z
2000P;Generic Platform

It wil download to above patch 4 times.

Only 2000P;Generic Platform
will download 1 time.

Regards,

Pafke

**Comment by MarisElsins** [comment]
Hi,

thanks for reporting this issue.

Could you post the whole log of how you initiate getMOSPatch and what's printed to the screen, please?

Maris

**Comment by MarisElsins** [comment]
OK, I understand the issue now.

The problem is that if you query for patches for a specific platform then the Generic patches are automatically included in the search results returned by Oracle. That's why you get the same patch 4 times. 
I think I will not try to solve this issue because it requires me to make some assumptions on what the search results will be, and I don't want to do that to avoid other potential issues in the future.

The only possible way to try to address this is to check if the file that's about to be downloaded is already present and of the same size. If it is - then I could skip the downloading.

I'll consider that for the future.
